name = "mini-theater-review-loop"
compatibility_date = "2026-07-08"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "mini-theater"
database_id = "9d9a8905-16ed-4126-90a6-635c75a89ddb"
